[pytest]
# Allows "from conftest import ..." in qa/ tests to resolve properly in IDEs.
# The qa/ and tests/ conftest files are found automatically by pytest.
pythonpath = qa tests
testpaths = tests qa
